replicaCount: 3

image:
  repository: idjohnson/freshmvcapp
  tag: 0.2
  pullPolicy: IfNotPresent
  port: 8080

service:
  type: ClusterIP
  port: 80

env:
  dbHost: your_host
  dbName: patientsdb
  dbUser: your_username
  dbPort: 5432
  dbPassword: your_db_password # This will be overridden by the secret

otel:
  protocol: "http/protobuf" # or grpc
  endpoint: "https://otlp.nr-data.net:4318/v1/traces"
  servicename: "MvcPatients"
  headers: "api-key=ba2269284ec354ec699572be2a5c50e6FFFFNRAL"
  attributes: "app=MvcPatients"

imagePullSecrets: [] # Add your secret name here if needed

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}